name: reviewdog

on:
  pull_request:

jobs:
  golangci-lint:
    name: lint checks by using golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_version: 1.46.2
